AWSTemplateFormatVersion: "2010-09-09"
Description: "Image Labeling Application - S3 bucket with Lambda function for automatic image labeling using Amazon Rekognition"

Resources:
  # S3 Bucket for storing images and labels
  ImageBucket:
    Type: AWS::S3::Bucket
    DependsOn: LambdaInvokePermission
    Properties:
      BucketName: bluestone-image-labeling-a08324be2c5f
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt LabelImageFunction.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: uploads/
                  - Name: suffix
                    Value: .jpg
          - Event: s3:ObjectCreated:*
            Function: !GetAtt LabelImageFunction.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: uploads/
                  - Name: suffix
                    Value: .png
          - Event: s3:ObjectCreated:*
            Function: !GetAtt LabelImageFunction.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: uploads/
                  - Name: suffix
                    Value: .jpeg

  # IAM Role for Lambda Function
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3AndRekognitionAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: "arn:aws:s3:::bluestone-image-labeling-a08324be2c5f/*"
              - Effect: Allow
                Action:
                  - rekognition:DetectLabels
                Resource: "*"

  # Lambda Function for Image Labeling
  LabelImageFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: bluestone_label_image
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 60
      MemorySize: 512
      Code:
        ZipFile: |
          import json
          import boto3
          import logging
          from datetime import datetime, timezone
          from urllib.parse import unquote_plus

          # Initialize AWS clients
          s3_client = boto3.client('s3')
          rekognition_client = boto3.client('rekognition')

          # Configure logging
          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          def lambda_handler(event, context):
              """
              Lambda function to label images using Amazon Rekognition.
              Triggered when an image is uploaded to the S3 bucket.
              """
              try:
                  # Parse the S3 event
                  for record in event['Records']:
                      bucket = record['s3']['bucket']['name']
                      key = unquote_plus(record['s3']['object']['key'])
                      
                      logger.info(f'Processing image: {key} from bucket: {bucket}')
                      
                      # Call Amazon Rekognition to detect labels
                      response = rekognition_client.detect_labels(
                          Image={
                              'S3Object': {
                                  'Bucket': bucket,
                                  'Name': key
                              }
                          },
                          MaxLabels=10,
                          MinConfidence=75
                      )
                      
                      # Extract labels from the response
                      labels = response['Labels']
                      logger.info(f'Detected {len(labels)} labels')
                      
                      # Format the results
                      results = {
                          'image': key,
                          'timestamp': datetime.now(timezone.utc).isoformat(),
                          'labels': [
                              {
                                  'name': label['Name'],
                                  'confidence': round(label['Confidence'], 2)
                              }
                              for label in labels
                          ]
                      }
                      
                      # Save the labels to S3
                      # Replace uploads/ with labels/ and change extension to .json
                      label_key = key.replace('uploads/', 'labels/', 1)
                      label_key = label_key.rsplit('.', 1)[0] + '.json'
                      
                      s3_client.put_object(
                          Bucket=bucket,
                          Key=label_key,
                          Body=json.dumps(results, indent=2),
                          ContentType='application/json'
                      )
                      
                      logger.info(f'Labels saved to: {label_key}')
                      
                  return {
                      'statusCode': 200,
                      'body': json.dumps({
                          'message': 'Image labeling completed successfully',
                          'processed_images': len(event['Records'])
                      })
                  }
                  
              except Exception as e:
                  logger.error(f'Error processing image: {str(e)}')
                  raise

  # Permission for S3 to invoke Lambda
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LabelImageFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: "arn:aws:s3:::bluestone-image-labeling-a08324be2c5f"
      SourceAccount: !Ref AWS::AccountId

  # Lambda function to list images
  ListImagesFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: list_images
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      Code:
        ZipFile: |
          import json
          import boto3

          BUCKET_NAME = 'bluestone-image-labeling-a08324be2c5f'
          s3_client = boto3.client('s3')

          def lambda_handler(event, context):
              try:
                  response = s3_client.list_objects_v2(Bucket=BUCKET_NAME, Prefix='uploads/')
                  keys = [obj["Key"] for obj in response.get("Contents", []) if "Key" in obj]
                  images = [
                      key.replace("uploads/", "")
                      for key in keys
                      if key != "uploads/" and key.lower().endswith((".jpg", ".jpeg", ".png"))
                  ]
                  return {
                      'statusCode': 200,
                      'headers': {
                          'Content-Type': 'application/json',
                          'Access-Control-Allow-Origin': '*'
                      },
                      'body': json.dumps(images)
                  }
              except Exception as e:
                  return {
                      'statusCode': 500,
                      'headers': {
                          'Content-Type': 'application/json',
                          'Access-Control-Allow-Origin': '*'
                      },
                      'body': json.dumps({'error': str(e)})
                  }

  # Lambda function to get labels
  GetLabelsFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: get_labels
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      Code:
        ZipFile: |
          import json
          import boto3

          BUCKET_NAME = 'bluestone-image-labeling-a08324be2c5f'
          s3_client = boto3.client('s3')

          def lambda_handler(event, context):
              try:
                  filename = event['pathParameters']['filename']
                  label_filename = filename.rsplit('.', 1)[0] + '.json'
                  
                  obj = s3_client.get_object(Bucket=BUCKET_NAME, Key=f'labels/{label_filename}')
                  labels = json.loads(obj['Body'].read().decode('utf-8'))
                  
                  return {
                      'statusCode': 200,
                      'headers': {
                          'Content-Type': 'application/json',
                          'Access-Control-Allow-Origin': '*'
                      },
                      'body': json.dumps(labels)
                  }
              except Exception as e:
                  return {
                      'statusCode': 404,
                      'headers': {
                          'Content-Type': 'application/json',
                          'Access-Control-Allow-Origin': '*'
                      },
                      'body': json.dumps({'error': str(e)})
                  }

  # API Gateway
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: image-labeling-api
      EndpointConfiguration:
        Types:
          - REGIONAL

  # API Gateway Resources
  ImagesResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: images

  LabelsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: labels

  LabelsFilenameResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !Ref LabelsResource
      PathPart: "{filename}"

  # API Gateway Methods
  ImagesMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ImagesResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ListImagesFunction.Arn}/invocations"

  LabelsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref LabelsFilenameResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetLabelsFunction.Arn}/invocations"

  # API Gateway Deployment
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ImagesMethod
      - LabelsMethod
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: prod

  # Lambda permissions for API Gateway
  ListImagesPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ListImagesFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "${ApiGateway}/*/GET/images"

  GetLabelsPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GetLabelsFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "${ApiGateway}/*/GET/labels/*"

  # IAM Role for Amplify
  AmplifyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: amplify.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AmplifyS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub "${ImageBucket.Arn}/*"
                  - !GetAtt ImageBucket.Arn

  # Amplify App
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: image-labeling-viewer
      Repository: https://github.com/blue-mimo/image_labelling.git
      AccessToken: "{{resolve:secretsmanager:arn:aws:secretsmanager:us-east-1:509219055438:secret:image-labelling-github-token-UKPANA:SecretString:token}}"
      IAMServiceRole: !GetAtt AmplifyRole.Arn
      EnvironmentVariables:
        - Name: BUCKET_NAME
          Value: !Ref ImageBucket
      BuildSpec: |
        version: 1
        backend:
          phases:
            build:
              commands:
                - chmod +x deploy.sh
                - ./deploy.sh
        frontend:
          phases:
            build:
              commands:
                - echo "Preparing static web app"
          artifacts:
            baseDirectory: web
            files:
              - index.html
              - favicon.ico

  # Amplify Branch
  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: main
      EnableAutoBuild: true

Outputs:
  BucketName:
    Description: Name of the S3 bucket for images
    Value: !Ref ImageBucket
    Export:
      Name: ImageLabelingBucketName

  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt LabelImageFunction.Arn
    Export:
      Name: ImageLabelingLambdaArn

  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref LabelImageFunction
    Export:
      Name: ImageLabelingLambdaName

  AmplifyAppUrl:
    Description: URL of the Amplify web application
    Value: !Sub "https://${AmplifyBranch.BranchName}.${AmplifyApp.DefaultDomain}"
    Export:
      Name: ImageLabelingWebAppUrl

  ApiGatewayUrl:
    Description: URL of the API Gateway
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod"
    Export:
      Name: ImageLabelingApiUrl
