@startditaa GUI

+---------------------+----------------------+----------------------+
| Filter Search Box   |                      |                      |
+---------------------+                      |                      |
| Active Filters Area |                      |                      |
+---------------------+    Selected Image    |     Labels Table     |
|                     |                      |                      |
|                     |                      |                      |
|                     |                      |                      |
|                     +----------------------+----------------------+
|     Image List      |                      |                      |
|  (max 12 entries)   |                      |                      |
|                     |                      |                      |
|                     |                      |                      |
|                     |  Image Upload Area   |  Upload Report Area  |
|                     |                      |                      |
|                     |                      |                      |
|                     |                      |                      |
+---------------------+                      |                      |
| Pagination Controls |                      |                      |
+---------------------+----------------------+----------------------+

@endditaa